spring:
  rabbitmq:
    host: localhost
#    port: 15672
#    username: guest
#    password: guest
#    template:
#      exchange: task_exchanger
#      default-receive-queue: task_queue
#server:
#  port: 9091
#  servlet:
#    context-path: /spring-rabbit
